### ISSUE TITLE
[v2 Beta] SDO download fails if previous request timed out

### ISSUE THREAD

**Issue by dawn-minion** [Daxbot/node-canopen#11]
Noticed this this morning, if an SDO download times out (With err: `SDO protocol timed out`), it seems subsequent requests to the same index+subindex fail immediately with a timeout as well.

Looking at the CAN dump, it does indeed send the expected CAN message on the write starting, but it does not send the SDO abort message once the timeout is reached, and the subsequent times it does not send anything at all.

**Comment by dawn-minion** [comment]
If I have time I will try and take a look into this today or tomorrow as well. Thanks for all your work here :)

**Comment by wilkinsw** [comment]
I see what you mean, I've got something similar happening.  I'll look into it today.

**Comment by wilkinsw** [comment]
Should be fixed now.  I was doing the SDO queuing by promise chaining, but that meant that if one transfer was rejected the whole chain would end.
