### ISSUE TITLE
SDO expedited uint32 download produces "general error"

### ISSUE THREAD

**Issue by johras** [Daxbot/node-canopen#15]
First bit (s) is not set in 4 byte expedited download and therefore a client replies with an error. |0x02 should be |0x03 in init_download function?

**Comment by wilkinsw** [comment]
Thanks for the report, I'll take a look. What version are you using?

**Comment by johras** [comment]
I'm using version 1.4.4

The issue is in SDO.js on line 332.
Lines 336 and 337 are probably unnecessary after change?

**Comment by wilkinsw** [comment]
Should be fixed now in version 1.4.7:
https://www.npmjs.com/package/canopen/v/1.4.7
