### ISSUE TITLE
Time producer gives days from 1970 instead of 1984

### ISSUE THREAD

**Issue by arkaheb258** [Daxbot/node-canopen#29]
TIME write function (time.js:128) uses conversion typeToRaw (eds.js:242) which operate on epoch timestamp.
For CANopen time producer offset should be 441763200 seconds.
[CAN-CiA.org](https://www.can-cia.org/can-knowledge/canopen/special-function-protocols/)
[Wikipedia](https://en.wikipedia.org/wiki/CANopen#Time_Stamp_Object_(TIME)_protocol)

**Comment by wilkinsw** [comment]
You're exactly right, I will fix that this week

**Comment by wilkinsw** [comment]
Should be fixed in 2.7.2
https://www.npmjs.com/package/canopen/v/2.7.2
