### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by binarybox** [Daxbot/node-canopen#39]
Hey, 
I looked through code and saw that the documentation is already really good. But it could be easier to work with if it had Typescript support. Did you ever think about doing something like this? 
For me it is a lot easier to work with, because my IDE tells me what functions are there and the documentation of the code. This could make it easier especially for people who are new to lower the bar for them. 
I started using your codebase and was working with the documentation. This is also valid and should be sustained, but TS is easier to work with then JS, because with the compile errors you avoid doing a lot of mistakes.

**Comment by wilkinsw** [comment]
That is not on the list, but if Typescript is backwards compatible with older versions of node (currently supporting >=12), then you are welcome to submit a pull request for it.

**Comment by gp3098** [comment]
Can't we use compilation tools like webpack or rollup or typescript to downgrade the generated code to support es5? 
It should be possible to support typescript in this way. 
Https://www.typescriptlang.org/tsconfig#target
Name | supported compilation targets. 
Node 8 | ES2017. 
Node 10 | ES2018. 
Node 12 | ES2019.
---
Default:
ES3
Allowed:
es3
es5
es6/es2015
es2016
es2017
es2018
es2019
es2020
es2021
es2022
esnext

**Comment by wilkinsw** [comment]
Adding Typescript is not something I have the bandwidth for in the foreseeable future. Happy to review and potentially merge it in if someone else wants to do it.
