### ISSUE TITLE
Does this run on windows?

### ISSUE THREAD

**Issue by Burf2k** [Daxbot/node-canopen#41]
I am trying to read a Can Bus USB device that support CanOpen on a windows machine but its failing with

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for socketcan@3.0.0: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by wilkinsw** [comment]
The "socketcan" library will only work on Linux, just like the error message says. I am not aware of any support for CAN devices on Windows outside of proprietary tools like PCAN.

What device are you trying to use?
