### ISSUE TITLE
Apply SDO timeout to each segment 

### ISSUE THREAD

**Issue by dawn-minion** [Daxbot/node-canopen#5]
I currently have a 10 second timeout set for SDO transfers, and I noticed that on segmented transfers the timeout is applied for the entire operation, and not per segment like I expected. Sometimes I need to send a ~100KB or so file to a device on my network, which takes 30-40 seconds or so. I would expect the 10 second timeout to count for each segment, not the entire transfer. 

Currently the timeout will trigger, despite the SDO transfer still working correctly. Ideally I'd only want the timeout to trigger when the device stops responding to an expected segment.

**Comment by wilkinsw** [comment]
Good point, I will fix that

**Comment by wilkinsw** [comment]
That should do it, feel free to re-open if I missed something!
